# Site settings
title: websrvr blog
email: support@websrvr.zendesk.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of websrvr, we'll post interesting updates about our
  features and our technology here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.websrvr.in" # the base hostname & protocol for your site
twitter_username: websrvr
permalink: /:title/

# Build settings
markdown: kramdown
destination: /home/minhajuddin/Dropbox/Apps/websrvr/websrvrblog
